### ISSUE TITLE
Mazes todo

### ISSUE THREAD

**Issue by ErikLambrechts** [ErikLambrechts/creative_code#2]
- [ ] Render on grid. Check grid example in vpype
- [ ] Vpype scale
- [ ] Simple depth first algorithm
- [ ] Grid base renderer
- [ ] Path renderer
- [ ] Wall renderer
- [ ] Bridges maze
- [ ] Hex grid
- [ ] 3D 
  - [ ] export to stl
  - [ ] blender inport

- [ ] Phidias base mazes
  - [ ]   Max lengeaddpoint on edge
  - [ ] Max distance between nodseds

**Comment by ErikLambrechts** [comment]
- [ ] Vpype occluded self intersection
